// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	model "github.com/mattermost/mattermost/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// PostReplyStore is an autogenerated mock type for the PostReplyStore type
type PostReplyStore struct {
	mock.Mock
}

// IncrDRcountByPostId provides a mock function with given fields: postId
func (_m *PostReplyStore) IncrDRcountByPostId(postId string) error {
	ret := _m.Called(postId)

	if len(ret) == 0 {
		panic("no return value specified for IncrDRcountByPostId")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(postId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: reply
func (_m *PostReplyStore) Save(reply *model.PostReply) error {
	ret := _m.Called(reply)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.PostReply) error); ok {
		r0 = rf(reply)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPostReplyStore creates a new instance of PostReplyStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostReplyStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostReplyStore {
	mock := &PostReplyStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
