// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	model "github.com/mattermost/mattermost/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// ReplyThreadsStore is an autogenerated mock type for the ReplyThreadsStore type
type ReplyThreadsStore struct {
	mock.Mock
}

// IncrReplyCountByPostId provides a mock function with given fields: postId
func (_m *ReplyThreadsStore) IncrReplyCountByPostId(postId string) error {
	ret := _m.Called(postId)

	if len(ret) == 0 {
		panic("no return value specified for IncrReplyCountByPostId")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(postId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: thread
func (_m *ReplyThreadsStore) Save(thread *model.ReplyThreads) error {
	ret := _m.Called(thread)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.ReplyThreads) error); ok {
		r0 = rf(thread)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReplyThreadsStore creates a new instance of ReplyThreadsStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReplyThreadsStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReplyThreadsStore {
	mock := &ReplyThreadsStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
